### ISSUE TITLE
Solve problem 2

### ISSUE THREAD

**Issue by andrewdacenko** [andrewdacenko/kpi-oop-master#5]
# Problem

Знайти у заданій директорії текстові файли, та підрахувати в кожному файлі кількість слів, що починаються із заданої літери. До деякого файлу записати назви таких файлів та кількість знайдених слів. Результат вивести на консоль. 
- [x] read list of txt files (#6)
- [x] read contents of each file (#7)
- [x] find number of matched words (#8)
- [x] write to separate file filenames and number of matches (#9)
